
name: Run unit tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch: {}

# If you trigger a new workflow while the previous one is running,
# this will cancel the previous one.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      # Use matrix strategy to run the tests on multiple Py versions on multiple OSs.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    
    env:
      BQ_PROJETO: ${{ secrets.PROJECT_ID }}
      API_CHAVE: ${{ secrets.API_CHAVE }}
      ARTEFATOS_PREDICAO_URI: ${{ secrets.ARTEFATOS_PREDICAO_URI }}
      JWT_ALGORITMO: HS256
      PORT: 8080
      TOKEN_VALIDADE_MINUTOS: 5256000000
  
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          make setup-local

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint

      - name: Run Tests
        run: |
          echo "Running the tests..."
          make test
